# Generated by Django 3.1.4 on 2020-12-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ImageField(null=True, upload_to='userMedia/'),
        ),
    ]
