# Generated by Django 3.1.4 on 2020-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='images',
            field=models.ImageField(null=True, upload_to='image_upload'),
        ),
    ]
