# Generated by Django 3.1.4 on 2020-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_cv_reader_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv_reader',
            name='created_ad',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
